
auth.token=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

defaults.org=peaktowertech
defaults.project=riderx_mobile_app

defaults.url=https://sentry.io/
